/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/players": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.players.id"];
          created_at?: parameters["rowFilter.players.created_at"];
          balance?: parameters["rowFilter.players.balance"];
          wins?: parameters["rowFilter.players.wins"];
          losses?: parameters["rowFilter.players.losses"];
          discord_name?: parameters["rowFilter.players.discord_name"];
          discord_server_id?: parameters["rowFilter.players.discord_server_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["players"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** players */
          players?: definitions["players"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.players.id"];
          created_at?: parameters["rowFilter.players.created_at"];
          balance?: parameters["rowFilter.players.balance"];
          wins?: parameters["rowFilter.players.wins"];
          losses?: parameters["rowFilter.players.losses"];
          discord_name?: parameters["rowFilter.players.discord_name"];
          discord_server_id?: parameters["rowFilter.players.discord_server_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.players.id"];
          created_at?: parameters["rowFilter.players.created_at"];
          balance?: parameters["rowFilter.players.balance"];
          wins?: parameters["rowFilter.players.wins"];
          losses?: parameters["rowFilter.players.losses"];
          discord_name?: parameters["rowFilter.players.discord_name"];
          discord_server_id?: parameters["rowFilter.players.discord_server_id"];
        };
        body: {
          /** players */
          players?: definitions["players"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/guilds": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.guilds.id"];
          created_at?: parameters["rowFilter.guilds.created_at"];
          guildId?: parameters["rowFilter.guilds.guildId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["guilds"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** guilds */
          guilds?: definitions["guilds"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.guilds.id"];
          created_at?: parameters["rowFilter.guilds.created_at"];
          guildId?: parameters["rowFilter.guilds.guildId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.guilds.id"];
          created_at?: parameters["rowFilter.guilds.created_at"];
          guildId?: parameters["rowFilter.guilds.guildId"];
        };
        body: {
          /** guilds */
          guilds?: definitions["guilds"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  /** @description Track player balances, and count wins and losses */
  players: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: bigint */
    balance?: number;
    /**
     * Format: integer
     * @default 0
     */
    wins?: number;
    /**
     * Format: integer
     * @default 0
     */
    losses?: number;
    /** Format: text */
    discord_name: string;
    /** Format: text */
    discord_server_id: string;
  };
  guilds: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: text */
    guildId: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description players */
  "body.players": definitions["players"];
  /** Format: bigint */
  "rowFilter.players.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.players.created_at": string;
  /** Format: bigint */
  "rowFilter.players.balance": string;
  /** Format: integer */
  "rowFilter.players.wins": string;
  /** Format: integer */
  "rowFilter.players.losses": string;
  /** Format: text */
  "rowFilter.players.discord_name": string;
  /** Format: text */
  "rowFilter.players.discord_server_id": string;
  /** @description guilds */
  "body.guilds": definitions["guilds"];
  /** Format: uuid */
  "rowFilter.guilds.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.guilds.created_at": string;
  /** Format: text */
  "rowFilter.guilds.guildId": string;
}

export interface operations {}

export interface external {}
