/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

/**
 *  npx openapi-typescript https://vetntcurweaavafzupoo.supabase.co/rest/v1/?apikey=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZldG50Y3Vyd2VhYXZhZnp1cG9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjQ1OTA4OTAsImV4cCI6MTk4MDE2Njg5MH0.Fx7nI37IFfJnhGNdpkkoY7gX67N7jby7Gwd3NThYTGs --output src/types/SupabaseTypes2.ts
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/players": {
    get: {
      parameters: {
        query: {
          /** database entry unique id */
          id?: parameters["rowFilter.players.id"];
          created_at?: parameters["rowFilter.players.created_at"];
          /** The amount of Guru Credits this user has */
          balance?: parameters["rowFilter.players.balance"];
          /** Total number of games the user has won */
          wins?: parameters["rowFilter.players.wins"];
          /** Total number of games the user has lost */
          losses?: parameters["rowFilter.players.losses"];
          /** Discord user's tag including #0000 */
          discord_name?: parameters["rowFilter.players.discord_name"];
          /** Discord server's unique identifier */
          discord_server_id?: parameters["rowFilter.players.discord_server_id"];
          /** Discord user's unique identifier */
          discord_id?: parameters["rowFilter.players.discord_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["players"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** players */
          players?: definitions["players"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          /** database entry unique id */
          id?: parameters["rowFilter.players.id"];
          created_at?: parameters["rowFilter.players.created_at"];
          /** The amount of Guru Credits this user has */
          balance?: parameters["rowFilter.players.balance"];
          /** Total number of games the user has won */
          wins?: parameters["rowFilter.players.wins"];
          /** Total number of games the user has lost */
          losses?: parameters["rowFilter.players.losses"];
          /** Discord user's tag including #0000 */
          discord_name?: parameters["rowFilter.players.discord_name"];
          /** Discord server's unique identifier */
          discord_server_id?: parameters["rowFilter.players.discord_server_id"];
          /** Discord user's unique identifier */
          discord_id?: parameters["rowFilter.players.discord_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          /** database entry unique id */
          id?: parameters["rowFilter.players.id"];
          created_at?: parameters["rowFilter.players.created_at"];
          /** The amount of Guru Credits this user has */
          balance?: parameters["rowFilter.players.balance"];
          /** Total number of games the user has won */
          wins?: parameters["rowFilter.players.wins"];
          /** Total number of games the user has lost */
          losses?: parameters["rowFilter.players.losses"];
          /** Discord user's tag including #0000 */
          discord_name?: parameters["rowFilter.players.discord_name"];
          /** Discord server's unique identifier */
          discord_server_id?: parameters["rowFilter.players.discord_server_id"];
          /** Discord user's unique identifier */
          discord_id?: parameters["rowFilter.players.discord_id"];
        };
        body: {
          /** players */
          players?: definitions["players"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/managedvoicechannels": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.managedvoicechannels.id"];
          created_at?: parameters["rowFilter.managedvoicechannels.created_at"];
          /** An array of managed VC's on a server */
          guildId?: parameters["rowFilter.managedvoicechannels.guildId"];
          channelId?: parameters["rowFilter.managedvoicechannels.channelId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["managedvoicechannels"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** managedvoicechannels */
          managedvoicechannels?: definitions["managedvoicechannels"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.managedvoicechannels.id"];
          created_at?: parameters["rowFilter.managedvoicechannels.created_at"];
          /** An array of managed VC's on a server */
          guildId?: parameters["rowFilter.managedvoicechannels.guildId"];
          channelId?: parameters["rowFilter.managedvoicechannels.channelId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.managedvoicechannels.id"];
          created_at?: parameters["rowFilter.managedvoicechannels.created_at"];
          /** An array of managed VC's on a server */
          guildId?: parameters["rowFilter.managedvoicechannels.guildId"];
          channelId?: parameters["rowFilter.managedvoicechannels.channelId"];
        };
        body: {
          /** managedvoicechannels */
          managedvoicechannels?: definitions["managedvoicechannels"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  /** @description Track player balances, and count wins and losses */
  players: {
    /**
     * Format: bigint
     * @description database entry unique id
     *
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /**
     * Format: bigint
     * @description The amount of Guru Credits this user has
     */
    balance?: number;
    /**
     * Format: integer
     * @description Total number of games the user has won
     * @default 0
     */
    wins?: number;
    /**
     * Format: integer
     * @description Total number of games the user has lost
     * @default 0
     */
    losses?: number;
    /**
     * Format: text
     * @description Discord user's tag including #0000
     */
    discord_name: string;
    /**
     * Format: text
     * @description Discord server's unique identifier
     */
    discord_server_id: string;
    /**
     * Format: text
     * @description Discord user's unique identifier
     */
    discord_id: string;
  };
  managedvoicechannels: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /**
     * Format: text
     * @description An array of managed VC's on a server
     */
    guildId: string;
    /** Format: text */
    channelId?: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description players */
  "body.players": definitions["players"];
  /**
   * Format: bigint
   * @description database entry unique id
   */
  "rowFilter.players.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.players.created_at": string;
  /**
   * Format: bigint
   * @description The amount of Guru Credits this user has
   */
  "rowFilter.players.balance": string;
  /**
   * Format: integer
   * @description Total number of games the user has won
   */
  "rowFilter.players.wins": string;
  /**
   * Format: integer
   * @description Total number of games the user has lost
   */
  "rowFilter.players.losses": string;
  /**
   * Format: text
   * @description Discord user's tag including #0000
   */
  "rowFilter.players.discord_name": string;
  /**
   * Format: text
   * @description Discord server's unique identifier
   */
  "rowFilter.players.discord_server_id": string;
  /**
   * Format: text
   * @description Discord user's unique identifier
   */
  "rowFilter.players.discord_id": string;
  /** @description managedvoicechannels */
  "body.managedvoicechannels": definitions["managedvoicechannels"];
  /** Format: uuid */
  "rowFilter.managedvoicechannels.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.managedvoicechannels.created_at": string;
  /**
   * Format: text
   * @description An array of managed VC's on a server
   */
  "rowFilter.managedvoicechannels.guildId": string;
  /** Format: text */
  "rowFilter.managedvoicechannels.channelId": string;
}

export interface operations {}

export interface external {}
